[package]
name = "bcs"
version = "0.1.4"
description = "Binary Canonical Serialization (BCS)"
repository = "https://github.com/zefchain/bcs"
readme = "README.md"
license = "Apache-2.0"
edition = "2018"

[dependencies]
thiserror = "=1.0.37"
serde = { version = "1.0.145", features = ["derive"] }

[dev-dependencies]
criterion = "0.3.6"
proptest = "0.10.1"
proptest-derive = "0.2.0"

[[bench]]
name = "bcs_bench"
harness = false
